name: Share data between jobs

on: [push]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          echo "$(expr 3 + 7)" > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: homework_pre
          path: math-homework.txt
          retention-days: 1

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: homework_pre
      - shell: bash
        run: |
          if [ ! -f math-homework.txt ]; then
            echo "Error: math-homework.txt not found"
            exit 1
          fi
          value=$(cat math-homework.txt)
          echo "$(expr $value \* 9)" > math-homework.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v4
        with:
          name: homework_final
          path: math-homework.txt
          retention-days: 1

  job_3:
    name: Display results
    needs: job_2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download math result for job 2
        uses: actions/download-artifact@v4
        with:
          name: homework_final
      - name: Print the final result
        shell: bash
        run: |
          if [ ! -f math-homework.txt ]; then
            echo "Error: math-homework.txt not found"
            exit 1
          fi
          value=$(cat math-homework.txt)
          echo "===================="
          echo "The result is: $value"
          echo "===================="