
name: react-build

on:
  push:
    branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4
            # Step 2: Install Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'
             

            # Step 3: Install dependencies
            - name: Install dependencies
              working-directory: ./my-app # Add this line
              run: npm install
              
            # Step 4: Build project build
            - name: Build project
              working-directory: ./my-app # Add this line
              run: npm build   
            # Step 5: Upload build results
            - name: Upload build results
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: my-app/build

    # test:
    #     runs-on: ubuntu-latest
    #     steps:    