
name: react-build

on:
  push:
    branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4
            # Step 2: Install Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                cache: 'pnpm'

            # Step 3: Install dependencies
            - name: Install dependencies
              run: npm install
            # Step 4: Build project build
            - name: Build project
              run: npm build   
            # Step 5: Upload build results
            - name: Upload build results
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: myapp/build

    # test:
    #     runs-on: ubuntu-latest
    #     steps:    