# This is a basic workflow to help you get started with Actions

name: segundo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
  job1:
      if: false  # This prevents the job from running
    # This workflow contains a single job called "build"
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      outputs:
        time: ${{ steps.step1.outputs.test }}
      steps:
        - id: step1
          run: echo "::set-output name=time::$(date)"
        - run: |
            echo "The time was ${{ steps.step1.outputs.test }} "
            echo "test=hallo" >> "$GITHUB_OUTPUT"

      # Steps represent a sequence of tasks that will be executed as part of the job
  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: use the output from the first job
        env:
          OUTPUT1: ${{ needs.job1.outputs.time }}
        run: echo "$OUTPUT1"
